[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
live_config_reload = true

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[cursor]
# blinking = "On"

[font]
size = 15

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000

[window]
dynamic_title = true
title = "Terminal"

[keyboard]
