[colors]
draw_bold_text_with_bright_colors = false

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[general]
live_config_reload = true


[colors.bright]
black   = "0x575279"
blue    = "0x7f8fa6"
cyan    = "0x8caaee"
green   = "0xa6d189"
magenta = "0xd2a6ff"
red     = "0xe78284"
white   = "0xe0def4"
yellow  = "0xe5c890"

[colors.cursor]
cursor = "0xe0def4"
text   = "0x575279"

[colors.normal]
black   = "0x575279"
blue    = "0x7f8fa6"
cyan    = "0x8caaee"
green   = "0xa6d189"
magenta = "0xd2a6ff"
red     = "0xe78284"
white   = "0xe0def4"
yellow  = "0xe5c890"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xe0def4"

[cursor]
# blinking = "On"

[env]
TERM = "alacritty"

[font]
size = 15

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000

[window]
dynamic_title = true
title = "Terminal"

[keyboard]
